dcache:
  build: .
  ports:
   - "2049:2049"
   - "2880:2880"
   - "22125:22125"
   - "22224:22224"
  volumes:
   - /space/docker-volumes/dcache-pools:/pools
   - /space/docker-volumes/docker-logs:/var/log/dcache
  links:
   - db:dcachedb
db:
  image: dcache/db-master

